# Generated by Django 5.2.5 on 2025-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('monthly', 'Monthly')], max_length=16),
        ),
    ]
